"""
A list of licenses based on the http://www.opendefinition.org/ list.
Defines license attributes such as name, url and rights granted.
"""

from collections import OrderedDict

# Not all licenses may have rights / requirements declared, but for those that
# do, this is what the keys mean
license_rights_info = {
'BY': 'Attribution required',
'NC': 'NonCommercial restriction',
'SA': 'ShareAlike requirement',
'ND': 'NoDerivatives restriction'
}

# No license can be considered "supported" until it has:
# a) a record below
# b) NC, SA and ND keys defined in that record

LICENSES = {
  "afl-3.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "afl-3.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Academic Free License 3.0 (AFL 3.0)", 
    "url": "http://www.opensource.org/licenses/afl-3.0.php"
  }, 
  "against-drm": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "against-drm", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Against DRM", 
    "url": "http://www.opendefinition.org/licenses/against-drm"
  }, 
  "agpl-v3": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "agpl-v3", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Affero GNU Public License", 
    "url": "http://www.opensource.org/licenses/agpl-v3.html"
  }, 
  "apache": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "apache", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Apache Software License", 
    "url": ""
  }, 
  "apache2.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "apache2.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Apache License, 2.0", 
    "url": "http://www.opensource.org/licenses/apache2.0.php"
  }, 
  "apl1.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "apl1.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Adaptive Public License", 
    "url": "http://www.opensource.org/licenses/apl1.0.php"
  }, 
  "apsl-2.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "apsl-2.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Apple Public Source License", 
    "url": "http://www.opensource.org/licenses/apsl-2.0.php"
  }, 
  "artistic-license-2.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "artistic-license-2.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Artistic license 2.0", 
    "url": "http://www.opensource.org/licenses/artistic-license-2.0.php"
  }, 
  "attribution": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "attribution", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Attribution Assurance Licenses", 
    "url": "http://www.opensource.org/licenses/attribution.php"
  }, 
  "bsd-license": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "bsd-license", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "New and Simplified BSD licenses", 
    "url": "http://www.opensource.org/licenses/bsd-license.php"
  }, 
  "bsl1.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "bsl1.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Boost Software License (BSL1.0)", 
    "url": "http://www.opensource.org/licenses/bsl1.0.html"
  }, 
  "ca-tosl1.1": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ca-tosl1.1", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Computer Associates Trusted Open Source License 1.1", 
    "url": "http://www.opensource.org/licenses/ca-tosl1.1.php"
  }, 
  "canada-crown": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "canada-crown", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Canadian Crown Copyright", 
    "url": ""
  }, 
  "cc-by": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-by", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons Attribution", 
    "url": "http://www.opendefinition.org/licenses/cc-by",
    # Rights and requirements
    'BY': True,
    'NC': False,
    'SA': False,
    'ND': False
  }, 
  "cc-by-sa": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-by-sa", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons Attribution Share-Alike", 
    "url": "http://www.opendefinition.org/licenses/cc-by-sa",
    # Rights and requirements
    'BY': True,
    'NC': False,
    'SA': True,
    'ND': False
  }, 
  "cc-nc": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-nc", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons Non-Commercial (Any)", 
    "url": "http://creativecommons.org/licenses/by-nc/2.0/",
    # Rights and requirements
    'BY': True,
    'NC': True,
    'SA': False,
    'ND': False
  }, 
  "cc-nc-sa": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-nc-sa", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons Non-Commercial Share-Alike (Any)", 
    "url": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
    # Rights and requirements
    'BY': True,
    'NC': True,
    'SA': True,
    'ND': False
  },
  "cc-nc-nd": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-nc-sa", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons Non-Commercial No-Derivatives (Any)", 
    "url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
    # Rights and requirements
    'BY': True,
    'NC': True,
    'SA': False,
    'ND': True
  }, 
 

  "cc-zero": {
    "domain_content": True, 
    "domain_data": True, 
    "domain_software": False, 
    "family": "", 
    "type": "cc-zero", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Creative Commons CCZero", 
    "url": "http://www.opendefinition.org/licenses/cc-zero",
    # Rights and requirements
    'BY': False,
    'NC': False,
    'SA': False,
    'ND': False
  }, 
  "cddl1": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "cddl1", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Common Development and Distribution License", 
    "url": "http://www.opensource.org/licenses/cddl1.php"
  }, 
  "cpal_1.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "cpal_1.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Common Public Attribution License 1.0 (CPAL)", 
    "url": "http://www.opensource.org/licenses/cpal_1.0"
  }, 
  "cuaoffice": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "cuaoffice", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "CUA Office Public License Version 1.0", 
    "url": "http://www.opensource.org/licenses/cuaoffice.php"
  }, 
  "dli-model-use": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "dli-model-use", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Statistics Canada: Data Liberation Initiative (DLI) - Model Data Use Licence", 
    "url": ""
  }, 
  "dsl": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "dsl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Design Science License", 
    "url": "http://www.opendefinition.org/licenses/dsl"
  }, 
  "ecl2": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ecl2", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Educational Community License, Version 2.0", 
    "url": "http://www.opensource.org/licenses/ecl2.php"
  }, 
  "eclipse-1.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "eclipse-1.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Eclipse Public License", 
    "url": "http://www.opensource.org/licenses/eclipse-1.0.php"
  }, 
  "eiffel": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "eiffel", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Eiffel Forum License", 
    "url": ""
  }, 
  "entessa": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "entessa", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Entessa Public License", 
    "url": "http://www.opensource.org/licenses/entessa.php"
  }, 
  "eudatagrid": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "eudatagrid", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "EU DataGrid Software License", 
    "url": "http://www.opensource.org/licenses/eudatagrid.php"
  }, 
  "fair": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "fair", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Fair License", 
    "url": "http://www.opensource.org/licenses/fair.php"
  }, 
  "fal": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "fal", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Free Art License", 
    "url": "http://www.opendefinition.org/licenses/fal"
  }, 
  "frameworx": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "frameworx", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Frameworx License", 
    "url": "http://www.opensource.org/licenses/frameworx.php"
  }, 
  "geo-no-fee-unrestricted": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "geo-no-fee-unrestricted", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "No Fee Unrestricted Use License Agreement For Government Geographic Data (Canada)", 
    "url": "http://www4.agr.gc.ca/AAFC-AAC/display-afficher.do?id=1226945498401&lang=eng"
  }, 
  "geogratis": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "geogratis", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Geogratis Licence Agreement", 
    "url": "http://geogratis.cgdi.gc.ca/geogratis/en/licence.jsp"
  }, 
  "gfdl": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "gfdl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU Free Documentation License", 
    "url": "http://www.opendefinition.org/licenses/gfdl"
  }, 
  "gpl-2.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "gpl-2.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU General Public License (GPL)", 
    "url": "http://www.opensource.org/licenses/gpl-2.0.php"
  }, 
  "gpl-3.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "gpl-3.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU General Public License version 3.0 (GPLv3)", 
    "url": "http://www.opensource.org/licenses/gpl-3.0.html"
  }, 
  "hesa-withrights": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "hesa-withrights", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Higher Education Statistics Agency Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "ibmpl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ibmpl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "IBM Public License", 
    "url": "http://www.opensource.org/licenses/ibmpl.php"
  }, 
  "intel-osl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "intel-osl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Intel Open Source License", 
    "url": ""
  }, 
  "ipafont": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ipafont", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "IPA Font License", 
    "url": "http://www.opensource.org/licenses/ipafont.html"
  }, 
  "isc-license": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "isc-license", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "ISC License", 
    "url": "http://www.opensource.org/licenses/isc-license.txt"
  }, 
  "jabber-osl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "jabber-osl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Jabber Open Source License", 
    "url": ""
  }, 
  "lgpl-2.1": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "lgpl-2.1", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU Library or \"Lesser\" General Public License (LGPL)", 
    "url": "http://www.opensource.org/licenses/lgpl-2.1.php"
  }, 
  "lgpl-3.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "lgpl-3.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "GNU Library or \"Lesser\" General Public License version 3.0 (LGPLv3)", 
    "url": "http://www.opensource.org/licenses/lgpl-3.0.html"
  }, 
  "localauth-withrights": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "localauth-withrights", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Local Authority Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "lucent-plan9": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "lucent-plan9", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Lucent Public License (Plan9)", 
    "url": ""
  }, 
  "lucent1.02": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "lucent1.02", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Lucent Public License Version 1.02", 
    "url": "http://www.opensource.org/licenses/lucent1.02.php"
  }, 
  "met-office-cp": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "met-office-cp", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Met Office UK Climate Projections Licence Agreement", 
    "url": "http://www.metoffice.gov.uk/climatechange/science/monitoring/ukcp09/UKCIP08_license_agreement_130709.pdf"
  }, 
  "miros": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "miros", 
    "is_okd_compliant": True, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "MirOS Licence", 
    "url": "http://www.opensource.org/licenses/miros.html"
  }, 
  "mit-license": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "mit-license", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "MIT license", 
    "url": "http://www.opensource.org/licenses/mit-license.php"
  }, 
  "mitre": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "mitre", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "MITRE Collaborative Virtual Workspace License (CVW License)", 
    "url": ""
  }, 
  "motosoto": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "motosoto", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Motosoto License", 
    "url": "http://www.opensource.org/licenses/motosoto.php"
  }, 
  "mozilla": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "mozilla", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Mozilla Public License 1.0 (MPL)", 
    "url": ""
  }, 
  "mozilla1.1": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "mozilla1.1", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Mozilla Public License 1.1 (MPL)", 
    "url": "http://www.opensource.org/licenses/mozilla1.1.php"
  }, 
  "ms-pl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ms-pl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Microsoft Public License (Ms-PL)", 
    "url": "http://www.opensource.org/licenses/ms-pl.html"
  }, 
  "ms-rl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ms-rl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Microsoft Reciprocal License (Ms-RL)", 
    "url": "http://www.opensource.org/licenses/ms-rl.html"
  }, 
  "multics": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "multics", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Multics License", 
    "url": "http://www.opensource.org/licenses/multics.txt"
  }, 
  "nasa1.3": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "nasa1.3", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "NASA Open Source Agreement 1.3", 
    "url": "http://www.opensource.org/licenses/nasa1.3.php"
  }, 
  "naumen": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "naumen", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Naumen Public License", 
    "url": "http://www.opensource.org/licenses/naumen.php"
  }, 
  "nethack": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "nethack", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Nethack General Public License", 
    "url": "http://www.opensource.org/licenses/nethack.php"
  }, 
  "nokia": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "nokia", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Nokia Open Source License", 
    "url": "http://www.opensource.org/licenses/nokia.php"
  }, 
  "nosl3.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "nosl3.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Non-Profit Open Software License 3.0 (Non-Profit OSL 3.0)", 
    "url": "http://www.opensource.org/licenses/NOSL3.0.html"
  }, 
  "notspecified": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "notspecified", 
    "is_generic": True, 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "License Not Specified", 
    "url": ""
  }, 
  "ntp-license": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ntp-license", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "NTP License", 
    "url": "http://www.opensource.org/licenses/ntp-license.php"
  }, 
  "oclc2": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "oclc2", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "OCLC Research Public License 2.0", 
    "url": "http://www.opensource.org/licenses/oclc2.php"
  }, 
  "odc-by": {
    "domain_content": False, 
    "domain_data": True, 
    "domain_software": False, 
    "family": "", 
    "type": "odc-by", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Attribution License", 
    "url": "http://www.opendefinition.org/licenses/odc-by"
  }, 
  "odc-odbl": {
    "domain_content": False, 
    "domain_data": True, 
    "domain_software": False, 
    "family": "", 
    "type": "odc-odbl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Open Database License (ODbL)", 
    "url": "http://www.opendefinition.org/licenses/odc-odbl"
  }, 
  "odc-pddl": {
    "domain_content": False, 
    "domain_data": True, 
    "domain_software": False, 
    "family": "", 
    "type": "odc-pddl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Data Commons Public Domain Dedication and Licence (PDDL)", 
    "url": "http://www.opendefinition.org/licenses/odc-pddl"
  }, 
  "openfont": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "openfont", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Font License 1.1 (OFL 1.1)", 
    "url": "http://www.opensource.org/licenses/openfont.html"
  }, 
  "opengroup": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "opengroup", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Group Test Suite License", 
    "url": "http://www.opensource.org/licenses/opengroup.php"
  }, 
  "osl-3.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "osl-3.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Open Software License 3.0 (OSL 3.0)", 
    "url": "http://www.opensource.org/licenses/osl-3.0.php"
  }, 
  "other-at": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "other-at", 
    "is_generic": True, 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Attribution)", 
    "url": ""
  }, 
  "other-closed": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "other-closed", 
    "is_generic": True, 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Not Open)", 
    "url": ""
  }, 
  "other-nc": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "other-nc", 
    "is_generic": True, 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Non-Commercial)", 
    "url": ""
  }, 
  "other-open": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "other-open", 
    "is_generic": True, 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Open)", 
    "url": ""
  }, 
  "other-pd": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "other-pd", 
    "is_generic": True, 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Other (Public Domain)", 
    "url": ""
  }, 
  "php": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "php", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "PHP License", 
    "url": "http://www.opensource.org/licenses/php.php"
  }, 
  "postgresql": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "postgresql", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "The PostgreSQL License", 
    "url": "http://www.opensource.org/licenses/postgresql"
  }, 
  "pythonpl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "pythonpl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Python license", 
    "url": "http://www.opensource.org/licenses/pythonpl.php"
  }, 
  "pythonsoftfoundation": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "pythonsoftfoundation", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Python Software Foundation License", 
    "url": "http://www.opensource.org/licenses/PythonSoftFoundation.php"
  }, 
  "qtpl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "qtpl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Qt Public License (QPL)", 
    "url": "http://www.opensource.org/licenses/qtpl.php"
  }, 
  "real": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "real", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "RealNetworks Public Source License V1.0", 
    "url": "http://www.opensource.org/licenses/real.php"
  }, 
  "ricohpl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ricohpl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Ricoh Source Code Public License", 
    "url": "http://www.opensource.org/licenses/ricohpl.php"
  }, 
  "rpl1.5": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "rpl1.5", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Reciprocal Public License 1.5 (RPL1.5)", 
    "url": "http://www.opensource.org/licenses/rpl1.5.txt"
  }, 
  "simpl-2.0": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "simpl-2.0", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Simple Public License 2.0", 
    "url": "http://www.opensource.org/licenses/simpl-2.0.html"
  }, 
  "sleepycat": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "sleepycat", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Sleepycat License", 
    "url": "http://www.opensource.org/licenses/sleepycat.php"
  }, 
  "sun-issl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "sun-issl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Sun Industry Standards Source License (SISSL)", 
    "url": ""
  }, 
  "sunpublic": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "sunpublic", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Sun Public License", 
    "url": "http://www.opensource.org/licenses/sunpublic.php"
  }, 
  "sybase": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "sybase", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Sybase Open Watcom Public License 1.0", 
    "url": "http://www.opensource.org/licenses/sybase.php"
  }, 
  "tcl": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "tcl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "Talis Community License", 
    "url": "http://www.opendefinition.org/licenses/tcl"
  }, 
  "uk-ogl": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "uk-ogl", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Open Government Licence (OGL)", 
    "url": "http://reference.data.gov.uk/id/open-government-licence",
    # Rights and requirements
    'BY': True,
    'NC': False,
    'SA': False,
    'ND': False
  }, 
  "ukclickusepsi": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "ukclickusepsi", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Click Use PSI", 
    "url": ""
  }, 
  "ukcrown": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "ukcrown", 
    "is_okd_compliant": False, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Crown Copyright", 
    "url": ""
  }, 
  "ukcrown-withrights": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "ukcrown-withrights", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK Crown Copyright with data.gov.uk rights", 
    "url": ""
  }, 
  "ukpsi": {
    "domain_content": True, 
    "domain_data": False, 
    "domain_software": False, 
    "family": "", 
    "type": "ukpsi", 
    "is_okd_compliant": True, 
    "is_osi_compliant": False, 
    "maintainer": "", 
    "status": "active", 
    "title": "UK PSI Public Sector Information", 
    "url": "http://www.opendefinition.org/licenses/ukpsi"
  }, 
  "uoi-ncsa": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "uoi-ncsa", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "University of Illinois/NCSA Open Source License", 
    "url": "http://www.opensource.org/licenses/UoI-NCSA.php"
  }, 
  "ver2_eiffel": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "ver2_eiffel", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Eiffel Forum License V2.0", 
    "url": "http://www.opensource.org/licenses/ver2_eiffel.php"
  }, 
  "vovidapl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "vovidapl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Vovida Software License v. 1.0", 
    "url": "http://www.opensource.org/licenses/vovidapl.php"
  }, 
  "w3c": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "w3c", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "W3C License", 
    "url": "http://www.opensource.org/licenses/W3C.php"
  }, 
  "wxwindows": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "wxwindows", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "wxWindows Library License", 
    "url": "http://www.opensource.org/licenses/wxwindows.php"
  }, 
  "xnet": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "xnet", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "X.Net License", 
    "url": "http://www.opensource.org/licenses/xnet.php"
  }, 
  "zlib-license": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "zlib-license", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "zlib/libpng license", 
    "url": "http://www.opensource.org/licenses/zlib-license.php"
  }, 
  "zpl": {
    "domain_content": False, 
    "domain_data": False, 
    "domain_software": True, 
    "family": "", 
    "type": "zpl", 
    "is_okd_compliant": False, 
    "is_osi_compliant": True, 
    "maintainer": "", 
    "status": "active", 
    "title": "Zope Public License", 
    "url": "http://www.opensource.org/licenses/zpl.php"
  },

# Licenses added by OpenArticleGauge committers due to having to deal with them :)
  "plos-who": {
    "type": "plos-who",
    "title": "World Health Organisation (PLoS) License",
    # Rights and requirements
    'BY': True,
    'NC': None, # unknown - we can't decide
    'SA': False,
    'ND': False
  },
  "free-to-read": {
    "type": "free-to-read",
    "title": "Free to Read",
    # Rights and requirements
    'BY': None, # unknown - we can't decide
    'NC': None, 
    'SA': None,
    'ND': None,
    "comment" : "The publisher asserts using a badge or statement that this article is accessible. We cannot determine any specific re-use or use rights as there is no explicit statement or link to a license." 
   },
  "cc-by-nd": {
    "type": "cc-by-nd",
    "status": "active",
    "title": "Creative Commons Attribution-NoDerivatives (Any)",
    "url": "http://creativecommons.org/licenses/by-nd/4.0/",
    # Rights and requirements
    'BY': True,
    'NC': False,
    'SA': False,
    'ND': True
  },

}

# alias new license types to existing licenses by recording them in the aliases dict below
# "new type": "existing type", e.g. "cc-by-nc": "cc-nc" (the open definition only includes cc-nc, not cc-by-nc)
aliases = {'cc-by-nc': 'cc-nc', 'cc-by-nc-sa': 'cc-nc-sa', 'cc-by-nc-nd': 'cc-nc-nd'}
for alias, target in aliases.items():
    LICENSES[alias] = LICENSES[target]


licenses_dropdown = [('','')] # default: empty
__process_licenses = OrderedDict(sorted(LICENSES.items(), key=lambda x: x[1]['title'])).items() # in alphabetical order of the titles (shown to the user)

# Creative Commons first
for lic_type, info in __process_licenses[:]:
    if lic_type.startswith('cc-'):
        choice = (lic_type, info.get('title', lic_type))
        licenses_dropdown.append(choice)
        __process_licenses.remove((lic_type, info))

# Free to Read next
for lic_type, info in __process_licenses[:]:
    if lic_type == 'free-to-read':
        choice = (lic_type, info.get('title', lic_type))
        licenses_dropdown.append(choice)
        __process_licenses.remove((lic_type, info))

dropdown_separator = ('', '--------------------')
licenses_dropdown.append(dropdown_separator)

# Take out all "Other"-type licenses to append to end of options later
other_license_choices = []
for lic_type, info in __process_licenses[:]:
    if lic_type.startswith('other-'):
        choice = (lic_type, info.get('title', lic_type))
        other_license_choices.append(choice)
        __process_licenses.remove((lic_type, info))

# the rest
for lic_type, info in __process_licenses:
    choice = (lic_type, info.get('title', lic_type))
    licenses_dropdown.append(choice)

licenses_dropdown.append(dropdown_separator)

# now append "Other"-type licenses to the end of the options
licenses_dropdown += other_license_choices
